# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'permissions': (('view_draft_post', 'Can view draft posts'),)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag_list',
        ),
    ]
