# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161222_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published'),
        ),
    ]
