# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161222_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(help_text='URL name for post', max_length=110),
        ),
    ]
