# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161228_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'date_added', 'ordering': ['-date_added', 'title'], 'permissions': (('user_change_own_post', 'User is allowed to add/edit/remove his own posts'),)},
        ),
    ]
